"""
Django settings for sushi_project project.

Generated by 'django-admin startproject' using Django 4.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

#import logging
# import sys


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-16j1_2t+39o%0_o!@44wcu=fz_^14+9_)b^nd$xij&*_$*i4xx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# os.getenv("DEBUG", "True").lower() in ("1", "true", "yes")

# ALLOWED_HOSTS: prefer env var (comma-separated). Always include your production domain.
# _allowed_hosts_env = os.getenv("ALLOWED_HOSTS", "").strip()
# if _allowed_hosts_env:
#     ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(",") if h.strip()]
# elif DEBUG:
#     ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
# else:
    # Production fallback: include your domain(s).
ALLOWED_HOSTS = ["www.sushi4123.eu", "sushi4123.eu", "127.0.0.1", "localhost"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sushi',  # Your sushi application
]

AUTH_USER_MODEL = 'sushi.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # For serving static files in production
]

ROOT_URLCONF = 'sushi_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sushi_project.wsgi.application'
ASGI_APPLICATION = "sushi_project.asgi.application" 

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# URL to redirect to for login, especially for views using @login_required
LOGIN_URL = 'admin_login'


# settings.py
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')  


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-relay.brevo.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# EMAIL_PORT = 465
EMAIL_USE_SSL = False
# EMAIL_USE_TLS = False
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER',)
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD',)       # Gmail App Password (not your Gmail password)
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_TIMEOUT = 30
BREVO_API_KEY =os.environ.get('BREVO_API_KEY')

# # Logging: console + file to help diagnose worker timeouts / view errors
# LOG_LEVEL = os.getenv("DJANGO_LOG_LEVEL", "INFO").upper()
# LOG_DIR = BASE_DIR / "logs"
# os.makedirs(LOG_DIR, exist_ok=True)

# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "formatters": {
#         "verbose": {
#             "format": "[%(asctime)s] %(levelname)s %(name)s %(message)s"
#         },
#         "simple": {"format": "%(levelname)s %(message)s"},
#     },
#     "handlers": {
#         "console": {
#             "class": "logging.StreamHandler",
#             "formatter": "verbose",
#             "stream": sys.stdout,
#         },
#         "file": {
#             "class": "logging.handlers.RotatingFileHandler",
#             "filename": str(LOG_DIR / "django.log"),
#             "maxBytes": 10 * 1024 * 1024,
#             "backupCount": 5,
#             "formatter": "verbose",
#         },
#     },
#     "loggers": {
#         "": {  # root logger
#             "handlers": ["console", "file"],
#             "level": LOG_LEVEL,
#         },
#         "django.request": {
#             "handlers": ["console", "file"],
#             "level": "ERROR",
#             "propagate": False,
#         },
#         "sushi": {
#             "handlers": ["console", "file"],
#             "level": LOG_LEVEL,
#             "propagate": False,
#         },
#     },
# }

# # Optional: enable Django to include request info in logs (useful for DisallowedHost and request-time debugging)
# if DEBUG:
#     # keep default simple behavior locally
#     pass
# else:
#     # In production, ensure DEBUG is False and errors are logged
#     SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")